# Change all values in a column to lowercase.

In [1]:
import pandas as pd
df = pd.read_csv('students.csv')
df

       Name  Age  Marks  Gender      City
0      John   20   85.0    Male  New York
1     Alice   21   92.0  Female    London
2       Bob   19   45.0    Male     Paris
3      Emma   22    NaN  Female    London
4     David   20  110.0    Male  New York
5    Sophia   23   78.0  Female     Paris
6   Michael   21  150.0    Male     Tokyo
7    Olivia   20   65.0  Female    London
8      John   20   85.0    Male  New York
9      Liam   22    NaN    Male    Berlin
10     Noah   24   55.0    Male     Tokyo
11      Ava   21   99.0  Female     Paris

In [2]:
df['Name'] = df['Name'].str.lower()
df

       Name  Age  Marks  Gender      City
0      john   20   85.0    Male  New York
1     alice   21   92.0  Female    London
2       bob   19   45.0    Male     Paris
3      emma   22    NaN  Female    London
4     david   20  110.0    Male  New York
5    sophia   23   78.0  Female     Paris
6   michael   21  150.0    Male     Tokyo
7    olivia   20   65.0  Female    London
8      john   20   85.0    Male  New York
9      liam   22    NaN    Male    Berlin
10     noah   24   55.0    Male     Tokyo
11      ava   21   99.0  Female     Paris